0-module 1-task
js-tasks-ru/jsbasic-20210225_snejja pull request #1
Opened 2021-02-20 10:20 UTC by Snejja

2021-02-20 10:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-02-20 10:50 UTC, SinimaWath requested changes

2021-02-20 10:50 UTC, SinimaWath commented on 0-module/1-task/index.js
> +let sum = (m, n) => m + n;
Крутое, что используешь стрелочную функцию.

Но тогда тут нужно использовать `const`, так как перезаписывать функцию нельзя. На первой лекции, будем рассматривать их и я расскажу.

2021-02-26 11:25 UTC, Snejja commented on 0-module/1-task/index.js
> +let sum = (m, n) => m + n;
Исправила

2021-02-26 12:04 UTC, SinimaWath approved these changes

2021-02-26 12:04 UTC, merged