Added Homework 6-module
js-tasks-ru/jsbasic-20210225_snejja pull request #7
Opened 2021-03-29 09:36 UTC by Snejja

2021-03-29 18:46 UTC, SinimaWath requested changes

2021-03-29 18:46 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    return this.elem.querySelectorAll('button');
тут потенциальный баг.

если вдруг решать добавить, другую кнопку на страницу, не связанную с удалением, на нее в итоге тоже подпишеться твой метод. 

Нужно кнопку удаления, как-то отдельить, к примеру, через data-action

2021-03-29 18:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    });
Давай используем хелпер: `createElement` - который импортируется на первой строчке

2021-03-29 18:46 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    });
Давай используем хелпер: createElement - который импортируется на первой строчке

2021-03-29 18:46 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this._currentTranslateX += _slideWidth * direction;
Кажется, тут не имеет смысла писать в this, так как используешь только в одном месте. 

Лучше вынести в константу

2021-03-29 18:46 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    let slide = event.target.closest('.carousel__slide');
всегда на всякий, лучше проверить существование елемента:
`if (!slide) `

2021-03-29 18:46 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    let _slideWidth = this._carousel.offsetWidth;
Немного непонятно, зачем добавлять `_` к переменной

2021-03-30 11:43 UTC, Snejja commented on 6-module/1-task/index.js
> +    return this.elem.querySelectorAll('button');
Поняла, поправила

2021-03-30 11:44 UTC, Snejja commented on 6-module/2-task/index.js
> +    });
Поправила

2021-03-30 11:44 UTC, Snejja commented on 6-module/3-task/index.js
> +    });
Поправила

2021-03-30 11:44 UTC, Snejja commented on 6-module/3-task/index.js
> +    let slide = event.target.closest('.carousel__slide');
Спасибо, поняла. Поправила

2021-03-30 11:44 UTC, Snejja commented on 6-module/3-task/index.js
> +    let _slideWidth = this._carousel.offsetWidth;
Поправила

2021-03-30 11:48 UTC, Snejja commented on 6-module/3-task/index.js
> +    this._currentTranslateX += _slideWidth * direction;
Тут я не очень тебя поняла. Если вынести в константу, то это же не будет работать так как += . И область видимости не позволит даже let использовать.

2021-03-30 18:34 UTC, SinimaWath approved these changes

2021-03-30 18:34 UTC, merged